# Generated by Django 4.1.1 on 2022-10-03 16:41

import KindKaribe.models
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("KindKaribe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="utente", name="id",),
        migrations.RemoveField(model_name="utente", name="nome",),
        migrations.AddField(
            model_name="utente", name="Admin", field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="utente",
            name="CodiceFiscale",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="Cognome",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="utente", name="DataNascita", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="Email",
            field=models.EmailField(
                default="prova@gmail.com",
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="utente",
            name="Genere",
            field=enumchoicefield.fields.EnumChoiceField(
                default=KindKaribe.models.Genere(1),
                enum_class=KindKaribe.models.Genere,
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="utente",
            name="Ntelefono",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="utente",
            name="Password",
            field=models.CharField(default="prova", max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MetodoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Intestatario", models.CharField(max_length=200)),
                ("NumeroCarta", models.CharField(max_length=200)),
                ("MeseScadenza", models.IntegerField()),
                ("AnnoScadenza", models.IntegerField()),
                ("CVV", models.IntegerField()),
                (
                    "Circuito",
                    enumchoicefield.fields.EnumChoiceField(
                        default=KindKaribe.models.Circuito(1),
                        enum_class=KindKaribe.models.Circuito,
                        max_length=15,
                    ),
                ),
                (
                    "Possessore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="KindKaribe.utente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="utente",
            name="Nome",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
