# Generated by Django 4.1.1 on 2022-10-03 16:54

import KindKaribe.models
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "KindKaribe",
            "0002_remove_utente_id_remove_utente_nome_utente_admin_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "Nome",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("Descrizione", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nome", models.CharField(max_length=200)),
                (
                    "Tipo",
                    enumchoicefield.fields.EnumChoiceField(
                        default=KindKaribe.models.Tipo(2),
                        enum_class=KindKaribe.models.Tipo,
                        max_length=11,
                    ),
                ),
                (
                    "Peso",
                    enumchoicefield.fields.EnumChoiceField(
                        enum_class=KindKaribe.models.Peso, max_length=7, null=True
                    ),
                ),
                ("Prezzo", models.FloatField(default=0.0)),
                ("Descrizione", models.CharField(default="", max_length=200)),
                ("QuantitàDisponibile", models.IntegerField(default=0)),
                ("IVA", models.FloatField(default=0.0)),
                ("Visibile", models.BooleanField(default=1)),
                (
                    "Categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="KindKaribe.categoria",
                    ),
                ),
            ],
        ),
    ]
