# Generated by Django 4.1.1 on 2022-10-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("KindKaribe", "0003_categoria_prodotto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prodotto",
            old_name="QuantitàDisponibile",
            new_name="QuantitaDisponibile",
        ),
        migrations.CreateModel(
            name="Immagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("URL", models.CharField(default="default.jpg", max_length=200)),
                ("testoALT", models.CharField(default="ALT", max_length=200)),
                (
                    "Prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="KindKaribe.prodotto",
                    ),
                ),
            ],
        ),
    ]
