# Generated by Django 4.1.1 on 2022-10-03 17:43

import KindKaribe.models
from django.db import migrations
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "KindKaribe",
            "0004_rename_quantitàdisponibile_prodotto_quantitadisponibile_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="Peso",
            field=enumchoicefield.fields.EnumChoiceField(
                default="", enum_class=KindKaribe.models.Peso, max_length=7, null=True
            ),
        ),
    ]
